# Generated by Django 6.0.3 on 2026-03-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_rename_date_taken_to_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aperture',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='focal_length',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='shutter_speed',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
