# Generated by Django 6.0.3 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_move_unique_to_constraint_drop_validators_default_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
