# Generated by Django 6.0.3 on 2026-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_backfill_recipe_version_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash', ''), _negated=True), fields=('content_hash',), name='unique_image_content_hash'),
        ),
    ]
