# Generated by Django 6.0.3 on 2026-05-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_image_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipegroupmember',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='data.fujifilmrecipe'),
        ),
    ]
