# Generated by Django 6.0.3 on 2026-05-23 15:50, then hand-edited to add the
# Sensor seed step. The 9 sensor names are intentionally inlined here (not
# imported from src.data.sensors) so a migration replay reproduces the same
# rows even if SENSOR_NAMES is edited later — see the module docstring of
# src/data/sensors.py for how the two stay in lock-step.

from typing import Any

from django.db import migrations, models

# Sensors to seed. Order is preserved as the insertion order, but the table
# itself is unordered; ids are auto-assigned by the database.
_SENSOR_NAMES_TO_SEED = (
    "X-Trans I",
    "X-Trans II",
    "X-Trans III",
    "X-Trans IV",
    "X-Trans V",
    "GFX",
    "Bayer",
    "EXR-CMOS",
    "Full Spectrum",
)


def seed_sensors(apps: Any, schema_editor: Any) -> None:
    Sensor = apps.get_model("data", "Sensor")
    Sensor.objects.bulk_create([Sensor(name=name) for name in _SENSOR_NAMES_TO_SEED])


def unseed_sensors(apps: Any, schema_editor: Any) -> None:
    Sensor = apps.get_model("data", "Sensor")
    Sensor.objects.filter(name__in=_SENSOR_NAMES_TO_SEED).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_alter_recipegroupmember_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_sensor_name'),
        ),
        migrations.RunPython(seed_sensors, reverse_code=unseed_sensors),
        migrations.RemoveConstraint(
            model_name='fujifilmrecipe',
            name='unique_fujifilm_recipe',
        ),
        migrations.AddField(
            model_name='fujifilmrecipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fujifilmrecipe',
            name='sensor_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fujifilmrecipe',
            name='sensors',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='data.sensor'),
        ),
        migrations.AddConstraint(
            model_name='fujifilmrecipe',
            constraint=models.UniqueConstraint(
                fields=(
                    'film_simulation', 'dynamic_range', 'd_range_priority',
                    'grain_roughness', 'grain_size', 'color_chrome_effect',
                    'color_chrome_fx_blue', 'white_balance', 'white_balance_red',
                    'white_balance_blue', 'highlight', 'shadow', 'color',
                    'sharpness', 'high_iso_nr', 'clarity',
                    'monochromatic_color_warm_cool', 'monochromatic_color_magenta_green',
                    'sensor_signature',
                ),
                name='unique_fujifilm_recipe',
                nulls_distinct=False,
            ),
        ),
    ]
