# Generated by Django 6.0.3 on 2026-07-02 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_libraryfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=16)),
                ('total', models.IntegerField(null=True)),
                ('processed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('error_message', models.TextField(null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='data.libraryfolder')),
            ],
            options={
                'indexes': [models.Index(fields=['folder', '-started_at'], name='idx_sync_run_folder_started')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ('SCANNING', 'PROCESSING'))), fields=('folder',), name='unique_active_sync_run_per_folder')],
            },
        ),
    ]
