# Generated by Django 6.0.3 on 2026-08-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_syncrun'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syncrun',
            name='unique_active_sync_run_per_folder',
        ),
        migrations.AddField(
            model_name='libraryfolder',
            name='previous_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='missing_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='prune_mode',
            field=models.CharField(default='PRUNE_AUTO', max_length=16),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='prune_skipped',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='removed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='uncovered_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('SCANNING', 'PROCESSING', 'PRUNING'))), fields=('folder',), name='unique_active_sync_run_per_folder'),
        ),
    ]
