# Generated by Django 6.0.3 on 2026-08-09 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_syncrun_prune_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=1024)),
                ('reason', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True, default='')),
                ('file_size', models.BigIntegerField()),
                ('file_modified_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_images', to='data.libraryfolder')),
            ],
            options={
                'indexes': [models.Index(fields=['folder', 'reason'], name='idx_ignored_image_folder')],
                'constraints': [models.UniqueConstraint(fields=('filepath',), name='unique_ignored_image_filepath')],
            },
        ),
    ]
