# Generated by Django 6.0.3 on 2026-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_ignoredimage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-taken_at', 'id'], name='image_taken_at_id_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-rating', '-taken_at', 'id'], name='image_rating_taken_id_idx'),
        ),
    ]
