# Generated by Django 6.0.3 on 2026-09-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_image_image_taken_at_id_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syncrun',
            name='unique_active_sync_run_per_folder',
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('SCANNING', 'PROCESSING', 'PRUNING', 'REMOVING'))), fields=('folder',), name='unique_active_sync_run_per_folder'),
        ),
    ]
