# Generated by Django 6.0.3 on 2026-09-24 21:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_remove_syncrun_unique_active_sync_run_per_folder_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipegroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('group_type', 'COLLECTION')), name='unique_collection_name_ci'),
        ),
    ]
